#
###################################
# Site wide configuration
####################################
#
title: Haebom's Blog
email:
description: 보고, 듣고, 익힌 것
url: https://haebom.github.io/


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Haebom
  avatar: leonids-logo.png
  job:
  bio:
  email:
  disqus-shortname: haebom
  twitter: haebomi
  facebook: #username
  google:
    plus: #username
    analytics: UA-97717979-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: haebom
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
